from .welcome import Welcome
from .prepare_arcaeaOfflineOcr import Prepare_ArcaeaOfflineOcr
from .prepare_tesseract import Prepare_Tesseract
from .device_select import Device_Select
from .crop_introduction import Crop_Introduction
from .crop_selectScreenshot import Crop_SelectScreenshot
from .crop_pure import Crop_Pure
from .crop_far import Crop_Far
from .crop_lost import Crop_Lost
from .crop_score import Crop_Score
from .crop_max_recall import Crop_MaxRecall
from .crop_rating_class import Crop_RatingClass
from .crop_title import Crop_Title
from .final_confirm import Final_Confirm
